export const country = [
  "Mauritania",
  "Eritrea",
  "Puerto Rico",
  "Romania",
  "Antigua and Barbuda",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Chile",
  "Ghana",
  "Gibraltar",
  "Venezuela",
  "Kosovo",
  "Botswana",
  "Tanzania",
  "Montenegro",
  "Comoros",
  "Ivory Coast",
  "Cape Verde",
  "Lesotho",
  "Gabon",
  "Grenada",
  "Jordan",
  "Sweden",
  "Vietnam",
  "Qatar",
  "Brazil",
  "Finland",
  "Georgia",
  "Senegal",
  "South Korea",
  "Anguilla",
  "São Tomé and Príncipe",
  "Antarctica",
  "Guyana",
  "Nauru",
  "Suriname",
  "Cambodia",
  "Curaçao",
  "Maldives",
  "Paraguay",
  "Peru",
  "France",
  "Falkland Islands",
  "Uzbekistan",
  "Egypt",
  "United States Minor Outlying Islands",
  "Dominica",
  "Israel",
  "Monaco",
  "Republic of the Congo",
  "Ireland",
  "French Southern and Antarctic Lands",
  "Kazakhstan",
  "Malaysia",
  "United Arab Emirates",
  "Czechia",
  "Yemen",
  "Myanmar",
  "Saint Kitts and Nevis",
  "United States Virgin Islands",
  "French Polynesia",
  "Fiji",
  "Albania",
  "Isle of Man",
  "Australia",
  "Caribbean Netherlands",
  "Italy",
  "Afghanistan",
  "Kyrgyzstan",
  "Wallis and Futuna",
  "United States",
  "Martinique",
  "Philippines",
  "Serbia",
  "Saint Helena, Ascension and Tristan da Cunha",
  "British Indian Ocean Territory",
  "Moldova",
  "Hong Kong",
  "Pakistan",
  "Saudi Arabia",
  "Angola",
  "New Caledonia",
  "Lithuania",
  "Netherlands",
  "Greenland",
  "Vatican City",
  "Micronesia",
  "Heard Island and McDonald Islands",
  "Kuwait",
  "Switzerland",
  "Saint Lucia",
  "Turks and Caicos Islands",
  "Malta",
  "Tonga",
  "Guatemala",
  "Uganda",
  "Guinea",
  "American Samoa",
  "Sint Maarten",
  "Nepal",
  "Slovenia",
  "British Virgin Islands",
  "Ethiopia",
  "Kiribati",
  "Guam",
  "Togo",
  "Papua New Guinea",
  "Iceland",
  "Northern Mariana Islands",
  "Austria",
  "Morocco",
  "South Georgia",
  "Iraq",
  "Liechtenstein",
  "Dominican Republic",
  "Ecuador",
  "Sierra Leone",
  "Belize",
  "Bhutan",
  "Iran",
  "Bolivia",
  "Turkey",
  "Faroe Islands",
  "Saint Barthélemy",
  "Greece",
  "India",
  "Nicaragua",
  "Central African Republic",
  "DR Congo",
  "Mali",
  "Azerbaijan",
  "Singapore",
  "Cuba",
  "Bangladesh",
  "Marshall Islands",
  "Bouvet Island",
  "Latvia",
  "Hungary",
  "Åland Islands",
  "Bulgaria",
  "Seychelles",
  "Cameroon",
  "Macau",
  "Mexico",
  "Brunei",
  "Taiwan",
  "Aruba",
  "Trinidad and Tobago",
  "Vanuatu",
  "Algeria",
  "Cook Islands",
  "Burundi",
  "Belarus",
  "North Korea",
  "Saint Martin",
  "Samoa",
  "Zimbabwe",
  "Bermuda",
  "Djibouti",
  "United Kingdom",
  "Niue",
  "Guinea-Bissau",
  "Japan",
  "Tuvalu",
  "Réunion",
  "Sudan",
  "North Macedonia",
  "Canada",
  "Indonesia",
  "Gambia",
  "Somalia",
  "Mauritius",
  "Montserrat",
  "Russia",
  "Portugal",
  "Oman",
  "Christmas Island",
  "Croatia",
  "Mongolia",
  "Tajikistan",
  "Solomon Islands",
  "Haiti",
  "Honduras",
  "Namibia",
  "Argentina",
  "Niger",
  "Timor-Leste",
  "Western Sahara",
  "Uruguay",
  "Barbados",
  "Guernsey",
  "Estonia",
  "Kenya",
  "Jamaica",
  "Luxembourg",
  "Guadeloupe",
  "Tunisia",
  "Cayman Islands",
  "Mozambique",
  "Tokelau",
  "Germany",
  "Liberia",
  "Pitcairn Islands",
  "Saint Pierre and Miquelon",
  "South Sudan",
  "Slovakia",
  "Palau",
  "Cyprus",
  "Libya",
  "Mayotte",
  "Turkmenistan",
  "Equatorial Guinea",
  "Nigeria",
  "Norway",
  "Bosnia and Herzegovina",
  "South Africa",
  "Denmark",
  "Laos",
  "Madagascar",
  "El Salvador",
  "Andorra",
  "Sri Lanka",
  "Rwanda",
  "Armenia",
  "Chad",
  "Benin",
  "Syria",
  "Spain",
  "Thailand",
  "Svalbard and Jan Mayen",
  "Ukraine",
  "China",
  "Malawi",
  "Panama",
  "Bahrain",
  "Saint Vincent and the Grenadines",
  "Jersey",
  "Burkina Faso",
  "Poland",
  "Belgium",
  "Bahamas",
  "Costa Rica",
  "San Marino",
  "New Zealand",
  "French Guiana",
  "Norfolk Island",
  "Lebanon",
  "Zambia",
  "Eswatini",
];
